/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("items").del();
  await knex("items").insert([
    {
      item_id: 1,
      name: "Antique Watch",
      description: "Beautiful antique watch, perfect for collectors.",
      category: "Antiques",
      start_bid: 100,
      highest_bid: 100,
      expiration_date: "2024-04-10",
      expiration_time: "18:00:00",
      user_id: 3,
    },
    {
      item_id: 2,
      name: "Vintage Camera",
      description: "Classic vintage camera in excellent condition.",
      category: "Photography",
      start_bid: 150,
      highest_bid: 150,
      expiration_date: "2024-04-12",
      expiration_time: "20:00:00",
      user_id: 1,
    },
    {
      item_id: 3,
      name: "Oil Painting",
      description: "Stunning oil painting by a renowned artist.",
      category: "Art",
      start_bid: 200,
      highest_bid: 200,
      expiration_date: "2024-04-15",
      expiration_time: "16:00:00",
      user_id: 2,
    },
    {
      item_id: 4,
      name: "Handcrafted Jewelry",
      description: "Elegant handcrafted jewelry set with gemstones.",
      category: "Fashion",
      start_bid: 80,
      highest_bid: 80,
      expiration_date: "2024-04-18",
      expiration_time: "17:30:00",
      user_id: 3,
    },
    {
      item_id: 5,
      name: "Rare Coins Collection",
      description:
        "Collection of rare and valuable coins from around the world.",
      category: "Collectibles",
      start_bid: 250,
      highest_bid: 250,
      expiration_date: "2024-04-20",
      expiration_time: "19:00:00",
      user_id: 1,
    },
    // {
    //   item_id: 6,
    //   name: "Vintage Vinyl Records",
    //   description:
    //     "Assorted collection of vintage vinyl records in excellent condition.",
    //   category: "Music",
    //   start_bid: 120,
    //   highest_bid: 120,
    //   expiration_date: "2024-04-22",
    //   expiration_time: "18:30:00",
    //   user_id: 2,
    // },
    // {
    //   item_id: 7,
    //   name: "Rare Books",
    //   description:
    //     "Collection of rare and first edition books from various genres.",
    //   category: "Books",
    //   start_bid: 180,
    //   highest_bid: 180,
    //   expiration_date: "2024-04-25",
    //   expiration_time: "15:00:00",
    //   user_id: 3,
    // },
    // {
    //   item_id: 8,
    //   name: "Vintage Posters",
    //   description:
    //     "Assorted collection of vintage posters featuring classic movies and events.",
    //   category: "Collectibles",
    //   start_bid: 90,
    //   highest_bid: 90,
    //   expiration_date: "2024-04-28",
    //   expiration_time: "16:45:00",
    //   user_id: 1,
    // },
    // {
    //   item_id: 9,
    //   name: "Rare Stamps",
    //   description: "Collection of rare and historic postage stamps.",
    //   category: "Collectibles",
    //   start_bid: 150,
    //   highest_bid: 150,
    //   expiration_date: "2024-05-01",
    //   expiration_time: "17:00:00",
    //   user_id: 2,
    // },
    // {
    //   item_id: 10,
    //   name: "Vintage Clothing",
    //   description:
    //     "Assorted collection of vintage clothing from different eras.",
    //   category: "Fashion",
    //   start_bid: 100,
    //   highest_bid: 100,
    //   expiration_date: "2024-05-04",
    //   expiration_time: "14:30:00",
    //   user_id: 3,
    // },
    // {
    //   item_id: 11,
    //   name: "Antique Furniture",
    //   description: "Beautiful antique furniture pieces in great condition.",
    //   category: "Antiques",
    //   start_bid: 300,
    //   highest_bid: 300,
    //   expiration_date: "2024-05-07",
    //   expiration_time: "16:00:00",
    //   user_id: 1,
    // },
    // {
    //   item_id: 12,
    //   name: "Vintage Toys",
    //   description: "Collection of vintage toys from the 20th century.",
    //   category: "Toys",
    //   start_bid: 80,
    //   highest_bid: 80,
    //   expiration_date: "2024-05-10",
    //   expiration_time: "18:30:00",
    //   user_id: 1,
    // },
    // {
    //   item_id: 13,
    //   name: "Classic Cars",
    //   description: "Assorted collection of classic cars in mint condition.",
    //   category: "Vehicles",
    //   start_bid: 5000,
    //   highest_bid: 5000,
    //   expiration_date: "2024-05-13",
    //   expiration_time: "20:00:00",
    //   user_id: 1,
    // },
    // {
    //   item_id: 14,
    //   name: "Rare Minerals",
    //   description: "Collection of rare minerals and gemstones.",
    //   category: "Collectibles",
    //   start_bid: 200,
    //   highest_bid: 200,
    //   expiration_date: "2024-05-16",
    //   expiration_time: "17:30:00",
    //   user_id: 1,
    // },
    // {
    //   item_id: 15,
    //   name: "Vintage Watches",
    //   description:
    //     "Assorted collection of vintage watches from prestigious brands.",
    //   category: "Fashion",
    //   start_bid: 150,
    //   highest_bid: 150,
    //   expiration_date: "2024-05-19",
    //   expiration_time: "19:00:00",
    //   user_id: 1,
    // },
    // {
    //   item_id: 16,
    //   name: "Rare Artifacts",
    //   description:
    //     "Collection of rare historical artifacts from different civilizations.",
    //   category: "Artifacts",
    //   start_bid: 300,
    //   highest_bid: 300,
    //   expiration_date: "2024-05-22",
    //   expiration_time: "18:30:00",
    //   user_id: 2,
    // },
    // {
    //   item_id: 17,
    //   name: "Vintage Maps",
    //   description:
    //     "Assorted collection of vintage maps depicting various regions.",
    //   category: "Collectibles",
    //   start_bid: 100,
    //   highest_bid: 100,
    //   expiration_date: "2024-05-25",
    //   expiration_time: "15:00:00",
    //   user_id: 2,
    // },
    // {
    //   item_id: 18,
    //   name: "Rare Pottery",
    //   description: "Collection of rare pottery pieces from different cultures.",
    //   category: "Art",
    //   start_bid: 120,
    //   highest_bid: 120,
    //   expiration_date: "2024-05-28",
    //   expiration_time: "16:45:00",
    //   user_id: 2,
    // },
    // {
    //   item_id: 19,
    //   name: "Vintage Coins",
    //   description: "Assorted collection of vintage coins from various periods.",
    //   category: "Collectibles",
    //   start_bid: 80,
    //   highest_bid: 80,
    //   expiration_date: "2024-06-01",
    //   expiration_time: "17:00:00",
    //   user_id: 2,
    // },
    // {
    //   item_id: 20,
    //   name: "Rare Books",
    //   description:
    //     "Collection of rare and first edition books from various genres.",
    //   category: "Books",
    //   start_bid: 180,
    //   highest_bid: 180,
    //   expiration_date: "2024-06-04",
    //   expiration_time: "14:30:00",
    //   user_id: 2,
    // },
    // {
    //   item_id: 21,
    //   name: "Vintage Postcards",
    //   description:
    //     "Assorted collection of vintage postcards featuring scenic views.",
    //   category: "Collectibles",
    //   start_bid: 50,
    //   highest_bid: 50,
    //   expiration_date: "2024-06-07",
    //   expiration_time: "16:00:00",
    //   user_id: 3,
    // },
    // {
    //   item_id: 22,
    //   name: "Rare Instruments",
    //   description:
    //     "Collection of rare musical instruments from different cultures.",
    //   category: "Music",
    //   start_bid: 200,
    //   highest_bid: 200,
    //   expiration_date: "2024-06-10",
    //   expiration_time: "18:30:00",
    //   user_id: 3,
    // },
    // {
    //   item_id: 23,
    //   name: "Vintage Furniture",
    //   description:
    //     "Assorted collection of vintage furniture pieces in excellent condition.",
    //   category: "Furniture",
    //   start_bid: 250,
    //   highest_bid: 250,
    //   expiration_date: "2024-06-13",
    //   expiration_time: "20:00:00",
    //   user_id: 3,
    // },
    // {
    //   item_id: 24,
    //   name: "Rare Art Prints",
    //   description: "Collection of rare art prints from famous artists.",
    //   category: "Art",
    //   start_bid: 150,
    //   highest_bid: 150,
    //   expiration_date: "2024-06-16",
    //   expiration_time: "17:30:00",
    //   user_id: 3,
    // },
    // {
    //   item_id: 25,
    //   name: "Vintage Jewelry",
    //   description:
    //     "Assorted collection of vintage jewelry pieces in various styles.",
    //   category: "Fashion",
    //   start_bid: 120,
    //   highest_bid: 120,
    //   expiration_date: "2024-06-19",
    //   expiration_time: "19:00:00",
    //   user_id: 3,
    // },
  ]);
};
