/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("bids").del();
  await knex("bids").insert([
    {
      bid_id: 1,
      amount: 150,
      user_id: 1,
      item_id: 1,
    },
    {
      bid_id: 2,
      amount: 200,
      user_id: 2,
      item_id: 2,
    },
    {
      bid_id: 3,
      amount: 180,
      user_id: 3,
      item_id: 3,
    },
    {
      bid_id: 4,
      amount: 120,
      user_id: 1,
      item_id: 4,
    },
    {
      bid_id: 5,
      amount: 250,
      user_id: 2,
      item_id: 5,
    },
    {
      bid_id: 6,
      amount: 300,
      user_id: 3,
      item_id: 6,
    },
    {
      bid_id: 7,
      amount: 90,
      user_id: 1,
      item_id: 7,
    },
    {
      bid_id: 8,
      amount: 120,
      user_id: 2,
      item_id: 8,
    },
    {
      bid_id: 9,
      amount: 200,
      user_id: 3,
      item_id: 9,
    },
    {
      bid_id: 10,
      amount: 150,
      user_id: 1,
      item_id: 10,
    },
    {
      bid_id: 11,
      amount: 180,
      user_id: 2,
      item_id: 11,
    },
    {
      bid_id: 12,
      amount: 100,
      user_id: 3,
      item_id: 12,
    },
    {
      bid_id: 13,
      amount: 250,
      user_id: 1,
      item_id: 13,
    },
    {
      bid_id: 14,
      amount: 300,
      user_id: 2,
      item_id: 14,
    },
    {
      bid_id: 15,
      amount: 200,
      user_id: 3,
      item_id: 15,
    },
    {
      bid_id: 16,
      amount: 180,
      user_id: 1,
      item_id: 16,
    },
    {
      bid_id: 17,
      amount: 150,
      user_id: 2,
      item_id: 17,
    },
    {
      bid_id: 18,
      amount: 120,
      user_id: 3,
      item_id: 18,
    },
    {
      bid_id: 19,
      amount: 250,
      user_id: 1,
      item_id: 19,
    },
    {
      bid_id: 20,
      amount: 200,
      user_id: 2,
      item_id: 20,
    },
    {
      bid_id: 21,
      amount: 180,
      user_id: 3,
      item_id: 21,
    },
    {
      bid_id: 22,
      amount: 150,
      user_id: 1,
      item_id: 22,
    },
    {
      bid_id: 23,
      amount: 120,
      user_id: 2,
      item_id: 23,
    },
    {
      bid_id: 24,
      amount: 250,
      user_id: 3,
      item_id: 24,
    },
    {
      bid_id: 25,
      amount: 200,
      user_id: 1,
      item_id: 25,
    },
    {
      bid_id: 26,
      amount: 180,
      user_id: 1,
      item_id: 1,
    },
    {
      bid_id: 27,
      amount: 120,
      user_id: 2,
      item_id: 2,
    },
    {
      bid_id: 28,
      amount: 250,
      user_id: 3,
      item_id: 3,
    },
    {
      bid_id: 29,
      amount: 200,
      user_id: 1,
      item_id: 4,
    },
    {
      bid_id: 30,
      amount: 150,
      user_id: 2,
      item_id: 5,
    },
    {
      bid_id: 31,
      amount: 180,
      user_id: 3,
      item_id: 6,
    },
    {
      bid_id: 32,
      amount: 120,
      user_id: 1,
      item_id: 7,
    },
    {
      bid_id: 33,
      amount: 250,
      user_id: 2,
      item_id: 8,
    },
    {
      bid_id: 34,
      amount: 200,
      user_id: 3,
      item_id: 9,
    },
    {
      bid_id: 35,
      amount: 150,
      user_id: 1,
      item_id: 10,
    },
    {
      bid_id: 36,
      amount: 180,
      user_id: 2,
      item_id: 11,
    },
    {
      bid_id: 37,
      amount: 100,
      user_id: 3,
      item_id: 12,
    },
    {
      bid_id: 38,
      amount: 250,
      user_id: 1,
      item_id: 13,
    },
    {
      bid_id: 39,
      amount: 300,
      user_id: 2,
      item_id: 14,
    },
    {
      bid_id: 40,
      amount: 200,
      user_id: 3,
      item_id: 15,
    },
    {
      bid_id: 41,
      amount: 180,
      user_id: 1,
      item_id: 16,
    },
    {
      bid_id: 42,
      amount: 150,
      user_id: 2,
      item_id: 17,
    },
    {
      bid_id: 43,
      amount: 120,
      user_id: 3,
      item_id: 18,
    },
    {
      bid_id: 44,
      amount: 250,
      user_id: 1,
      item_id: 19,
    },
    {
      bid_id: 45,
      amount: 200,
      user_id: 2,
      item_id: 20,
    },
    {
      bid_id: 46,
      amount: 180,
      user_id: 3,
      item_id: 21,
    },
    {
      bid_id: 47,
      amount: 150,
      user_id: 1,
      item_id: 22,
    },
    {
      bid_id: 48,
      amount: 120,
      user_id: 2,
      item_id: 23,
    },
    {
      bid_id: 49,
      amount: 250,
      user_id: 3,
      item_id: 24,
    },
    {
      bid_id: 50,
      amount: 200,
      user_id: 1,
      item_id: 25,
    },
  ]);
};
